### ISSUE TITLE
DEADLINE : 24일

### ISSUE THREAD

**Issue by jysong91** [jysong91/TeamSecond#11]
1. 회원가입 페이지 css적용
2. 마이페이지 구현 
3. 장소 상세보기 페이지 구현 
4. 장소 리스트로 보기 구현 
5. 리뷰쓰기 css적용 

+ 기타 사소한 작업들

**Comment by Tripredacus** [comment]
for Adun!

**Comment by jysong91** [comment]
장소 리스트로 보기 구현 - 미구현
